-- ============================================================================
-- Garba-Vortex stage 5 — storm mode
-- ----------------------------------------------------------------------------
-- Apply manually AFTER 20260927120000_garba_vortex.sql (do NOT db push):
--   supabase db query --linked -f supabase/migrations/20260927130000_garba_vortex_storm.sql
-- Idempotent. Re-running does NOT reset tuned garba_vortex_config values
-- and does NOT clear an in-progress storm flag.
--
-- When free-pin creates/bumps cross storm_global_writes_per_minute or
-- storm_region_writes_per_minute, the map stops serving isolated spikes.
-- get_garba_vortex_heatmap reads a coarse averaged snapshot (refreshed at
-- most every storm_snapshot_ttl_seconds). place_free_vortex_pin tightens
-- the daily cap and widens the bump radius. HTTP caching lives on
-- /api/garba-vortex-heatmap (Cache-Control), not in Postgres.
--
-- search_path matches live functions: public, extensions, net, pg_temp.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Tunables. Defaults fill the existing singleton; later edits stick.
-- ---------------------------------------------------------------------------
ALTER TABLE public.garba_vortex_config
  ADD COLUMN IF NOT EXISTS storm_mode text NOT NULL DEFAULT 'auto',
  ADD COLUMN IF NOT EXISTS storm_global_writes_per_minute integer NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS storm_region_writes_per_minute integer NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS storm_region_km integer NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS storm_snapshot_ttl_seconds integer NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS storm_free_pins_per_day integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS storm_bump_radius_m integer NOT NULL DEFAULT 500,
  ADD COLUMN IF NOT EXISTS storm_same_spot_radius_m integer NOT NULL DEFAULT 200,
  ADD COLUMN IF NOT EXISTS storm_cache_seconds integer NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS storm_cooldown_seconds integer NOT NULL DEFAULT 120,
  ADD COLUMN IF NOT EXISTS storm_release_ratio numeric NOT NULL DEFAULT 0.60,
  ADD COLUMN IF NOT EXISTS storm_cell_m integer NOT NULL DEFAULT 8000;

DO $storm_chk$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'garba_vortex_config_storm_ranges'
      AND conrelid = 'public.garba_vortex_config'::regclass
  ) THEN
    ALTER TABLE public.garba_vortex_config
      ADD CONSTRAINT garba_vortex_config_storm_ranges
      CHECK (
        storm_mode IN ('off', 'auto', 'on')
        AND storm_global_writes_per_minute BETWEEN 1 AND 100000
        AND storm_region_writes_per_minute BETWEEN 1 AND 100000
        AND storm_region_km BETWEEN 1 AND 500
        AND storm_snapshot_ttl_seconds BETWEEN 5 AND 3600
        AND storm_free_pins_per_day BETWEEN 0 AND 50
        AND storm_bump_radius_m BETWEEN 1 AND 50000
        AND storm_same_spot_radius_m BETWEEN 1 AND 50000
        AND storm_cache_seconds BETWEEN 5 AND 300
        AND storm_cooldown_seconds BETWEEN 0 AND 3600
        AND storm_release_ratio BETWEEN 0.05 AND 0.95
        AND storm_cell_m BETWEEN 500 AND 200000
      ) NOT VALID;
  END IF;
END
$storm_chk$;

ALTER TABLE public.garba_vortex_config VALIDATE CONSTRAINT garba_vortex_config_storm_ranges;

COMMENT ON COLUMN public.garba_vortex_config.storm_mode IS
  'off: never aggregate. auto: threshold + hysteresis. on: force the snapshot and the tighter free-pin cap.';

-- ---------------------------------------------------------------------------
-- Write ledger (owner only). Purged to 15 minutes inside the recorder.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.garba_vortex_write_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  creator_id uuid,
  lat double precision,
  lng double precision,
  region_key text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('create', 'bump'))
);

CREATE INDEX IF NOT EXISTS idx_garba_vortex_write_events_created
  ON public.garba_vortex_write_events (created_at);

CREATE INDEX IF NOT EXISTS idx_garba_vortex_write_events_region
  ON public.garba_vortex_write_events (region_key, created_at DESC);

ALTER TABLE public.garba_vortex_write_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.garba_vortex_write_events FROM PUBLIC;
REVOKE ALL ON TABLE public.garba_vortex_write_events FROM anon;
REVOKE ALL ON TABLE public.garba_vortex_write_events FROM authenticated;

COMMENT ON TABLE public.garba_vortex_write_events IS
  'Free-pin creates and bumps used to trip storm mode. No client access. Counts are not exposed by the public status RPC.';

-- ---------------------------------------------------------------------------
-- Storm flag. Insert once; re-runs keep the current active flag.
-- evaluated_at starts stale so the first map read evaluates immediately.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.garba_vortex_storm_state (
  id integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  active boolean NOT NULL DEFAULT false,
  reason text NOT NULL DEFAULT 'clear',
  global_writes integer NOT NULL DEFAULT 0,
  peak_region_writes integer NOT NULL DEFAULT 0,
  peak_region_key text,
  evaluated_at timestamptz NOT NULL DEFAULT now(),
  active_since timestamptz,
  snapshot_refreshed_at timestamptz
);

INSERT INTO public.garba_vortex_storm_state (id, evaluated_at)
VALUES (1, now() - interval '1 day')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.garba_vortex_storm_state ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.garba_vortex_storm_state FROM PUBLIC;
REVOKE ALL ON TABLE public.garba_vortex_storm_state FROM anon;
REVOKE ALL ON TABLE public.garba_vortex_storm_state FROM authenticated;

COMMENT ON TABLE public.garba_vortex_storm_state IS
  'Singleton storm flag. Admins read it through admin_get_garba_vortex_storm. The public map only receives storm + cache_seconds.';

-- ---------------------------------------------------------------------------
-- Coarse averaged heatmap. No black-hole column: storm never returns spikes.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.garba_vortex_heatmap_snapshot (
  grid_ix integer NOT NULL,
  grid_iy integer NOT NULL,
  lng double precision NOT NULL,
  lat double precision NOT NULL,
  weight numeric NOT NULL,
  point_count integer NOT NULL,
  report_count integer NOT NULL DEFAULT 0,
  max_severity integer NOT NULL,
  refreshed_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (grid_ix, grid_iy)
);

ALTER TABLE public.garba_vortex_heatmap_snapshot
  ADD COLUMN IF NOT EXISTS report_count integer NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_garba_vortex_heatmap_snapshot_bbox
  ON public.garba_vortex_heatmap_snapshot (lat, lng);

ALTER TABLE public.garba_vortex_heatmap_snapshot ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.garba_vortex_heatmap_snapshot FROM PUBLIC;
REVOKE ALL ON TABLE public.garba_vortex_heatmap_snapshot FROM anon;
REVOKE ALL ON TABLE public.garba_vortex_heatmap_snapshot FROM authenticated;

COMMENT ON TABLE public.garba_vortex_heatmap_snapshot IS
  'Storm heatmap. Weights are spatially averaged and singleton cells are dimmed. Refreshed on an interval, not per request.';

-- ---------------------------------------------------------------------------
-- Helpers (owner only)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.garba_vortex_region_key(
  p_lat double precision,
  p_lng double precision,
  p_km integer
)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, extensions, net, pg_temp
AS $$
  SELECT
    round(p_lat / (greatest(coalesce(p_km, 25), 1)::double precision / 111.32))::text
    || ':'
    || round(
      p_lng / (
        greatest(coalesce(p_km, 25), 1)::double precision
        / (111.32 * greatest(cos(radians(p_lat)), 0.2))
      )
    )::text;
$$;

REVOKE ALL ON FUNCTION public.garba_vortex_region_key(double precision, double precision, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.garba_vortex_region_key(double precision, double precision, integer) FROM anon;
REVOKE ALL ON FUNCTION public.garba_vortex_region_key(double precision, double precision, integer) FROM authenticated;

CREATE OR REPLACE FUNCTION public.garba_vortex_evaluate_storm()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions, net, pg_temp
AS $$
DECLARE
  v_cfg public.garba_vortex_config;
  v_state public.garba_vortex_storm_state;
  v_mode text;
  v_global integer := 0;
  v_peak integer := 0;
  v_peak_key text;
  v_active boolean;
  v_reason text;
  v_since timestamptz;
  v_ratio numeric;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('garba-storm'));

  SELECT * INTO v_cfg FROM public.garba_vortex_config WHERE id = 1;
  IF NOT FOUND THEN
    RETURN false;
  END IF;

  INSERT INTO public.garba_vortex_storm_state (id)
  VALUES (1)
  ON CONFLICT (id) DO NOTHING;

  SELECT * INTO v_state
  FROM public.garba_vortex_storm_state
  WHERE id = 1
  FOR UPDATE;

  SELECT count(*)::integer
    INTO v_global
  FROM public.garba_vortex_write_events
  WHERE created_at >= now() - interval '1 minute';

  SELECT e.region_key, count(*)::integer
    INTO v_peak_key, v_peak
  FROM public.garba_vortex_write_events e
  WHERE e.created_at >= now() - interval '1 minute'
  GROUP BY e.region_key
  ORDER BY count(*) DESC, e.region_key
  LIMIT 1;

  v_global := coalesce(v_global, 0);
  v_peak := coalesce(v_peak, 0);
  v_mode := coalesce(v_cfg.storm_mode, 'auto');
  v_ratio := least(0.95::numeric, greatest(0.05::numeric, coalesce(v_cfg.storm_release_ratio, 0.60)));

  IF v_mode = 'on' THEN
    v_active := true;
    v_reason := 'forced_on';
  ELSIF v_mode = 'off' THEN
    v_active := false;
    v_reason := 'forced_off';
  ELSIF NOT coalesce(v_state.active, false) THEN
    IF v_global >= v_cfg.storm_global_writes_per_minute THEN
      v_active := true;
      v_reason := 'global';
    ELSIF v_peak >= v_cfg.storm_region_writes_per_minute THEN
      v_active := true;
      v_reason := 'region';
    ELSE
      v_active := false;
      v_reason := 'clear';
    END IF;
  ELSE
    v_active := true;
    IF v_global >= v_cfg.storm_global_writes_per_minute THEN
      v_reason := 'global';
    ELSIF v_peak >= v_cfg.storm_region_writes_per_minute THEN
      v_reason := 'region';
    ELSIF v_global < (v_cfg.storm_global_writes_per_minute * v_ratio)
      AND v_peak < (v_cfg.storm_region_writes_per_minute * v_ratio)
      AND coalesce(v_state.active_since, now())
        <= now() - make_interval(secs => greatest(coalesce(v_cfg.storm_cooldown_seconds, 0), 0))
    THEN
      v_active := false;
      v_reason := 'clear';
    ELSE
      v_reason := 'cooldown';
    END IF;
  END IF;

  IF v_active THEN
    v_since := CASE
      WHEN coalesce(v_state.active, false) THEN coalesce(v_state.active_since, now())
      ELSE now()
    END;
  ELSE
    v_since := NULL;
  END IF;

  UPDATE public.garba_vortex_storm_state
     SET active = v_active,
         reason = v_reason,
         global_writes = v_global,
         peak_region_writes = v_peak,
         peak_region_key = v_peak_key,
         evaluated_at = now(),
         active_since = v_since
   WHERE id = 1;

  RETURN v_active;
END;
$$;

REVOKE ALL ON FUNCTION public.garba_vortex_evaluate_storm() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.garba_vortex_evaluate_storm() FROM anon;
REVOKE ALL ON FUNCTION public.garba_vortex_evaluate_storm() FROM authenticated;

COMMENT ON FUNCTION public.garba_vortex_evaluate_storm() IS
  'Owner-only. auto mode trips on global or per-region writes/minute and holds through storm_cooldown_seconds until both rates fall under storm_release_ratio.';

CREATE OR REPLACE FUNCTION public.garba_vortex_record_write(
  p_creator uuid,
  p_lat double precision,
  p_lng double precision,
  p_kind text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions, net, pg_temp
AS $$
DECLARE
  v_km integer;
  v_kind text := CASE WHEN p_kind = 'bump' THEN 'bump' ELSE 'create' END;
BEGIN
  SELECT storm_region_km INTO v_km FROM public.garba_vortex_config WHERE id = 1;
  v_km := greatest(coalesce(v_km, 25), 1);

  INSERT INTO public.garba_vortex_write_events (creator_id, lat, lng, region_key, kind)
  VALUES (
    p_creator,
    p_lat,
    p_lng,
    public.garba_vortex_region_key(p_lat, p_lng, v_km),
    v_kind
  );

  DELETE FROM public.garba_vortex_write_events
  WHERE created_at < now() - interval '15 minutes';

  PERFORM public.garba_vortex_evaluate_storm();
END;
$$;

REVOKE ALL ON FUNCTION public.garba_vortex_record_write(uuid, double precision, double precision, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.garba_vortex_record_write(uuid, double precision, double precision, text) FROM anon;
REVOKE ALL ON FUNCTION public.garba_vortex_record_write(uuid, double precision, double precision, text) FROM authenticated;

COMMENT ON FUNCTION public.garba_vortex_record_write(uuid, double precision, double precision, text) IS
  'Owner-only ledger row for a committed free-pin create or bump. Dry-runs must not call this.';

CREATE OR REPLACE FUNCTION public.refresh_garba_vortex_heatmap_snapshot(p_force boolean DEFAULT false)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions, net, pg_temp
AS $$
DECLARE
  v_ttl integer;
  v_cell_m integer;
  v_fresh timestamptz;
BEGIN
  SELECT storm_snapshot_ttl_seconds, storm_cell_m
    INTO v_ttl, v_cell_m
  FROM public.garba_vortex_config
  WHERE id = 1;

  v_ttl := greatest(coalesce(v_ttl, 60), 5);
  v_cell_m := greatest(coalesce(v_cell_m, 8000), 500);

  SELECT max(refreshed_at) INTO v_fresh FROM public.garba_vortex_heatmap_snapshot;
  IF NOT coalesce(p_force, false)
     AND v_fresh IS NOT NULL
     AND v_fresh >= now() - make_interval(secs => v_ttl) THEN
    RETURN false;
  END IF;

  -- Stampede guard. A waiter keeps serving the previous snapshot.
  IF NOT pg_try_advisory_xact_lock(hashtext('garba-storm-snapshot')) THEN
    RETURN false;
  END IF;

  SELECT max(refreshed_at) INTO v_fresh FROM public.garba_vortex_heatmap_snapshot;
  IF NOT coalesce(p_force, false)
     AND v_fresh IS NOT NULL
     AND v_fresh >= now() - make_interval(secs => v_ttl) THEN
    RETURN false;
  END IF;

  DELETE FROM public.garba_vortex_heatmap_snapshot;

  INSERT INTO public.garba_vortex_heatmap_snapshot (
    grid_ix, grid_iy, lng, lat, weight, point_count, report_count, max_severity, refreshed_at
  )
  WITH raw AS (
    SELECT
      round(
        m.location_lng / (
          v_cell_m::double precision / (111320.0 * greatest(cos(radians(m.location_lat)), 0.2))
        )
      )::integer AS ix,
      round(m.location_lat / (v_cell_m::double precision / 111320.0))::integer AS iy,
      avg(m.location_lng) AS lng,
      avg(m.location_lat) AS lat,
      count(*)::integer AS point_count,
      count(*) FILTER (
        WHERE coalesce(m.is_report, false)
          OR lower(coalesce(m.status::text, '')) = 'reported'
      )::integer AS report_count,
      max(m.severity_score)::integer AS max_severity,
      least(
        12::numeric,
        2.5
          + ln(count(*)::numeric + 1) * 1.7
          + ln(coalesce(sum(m.severity_score), 0)::numeric + 1) * 0.35
      ) AS weight
    FROM public.missions m
    WHERE m.hidden_at IS NULL
      AND m.location_lat IS NOT NULL
      AND m.location_lng IS NOT NULL
      AND public.garba_vortex_pin_visible(
        m.status::text,
        m.hidden_at,
        m.created_at,
        m.current_funding,
        m.history_public_until,
        m.media_purged_at
      )
    GROUP BY 1, 2
  ),
  glob AS (
    SELECT avg(weight) AS avg_weight FROM raw
  ),
  neigh AS (
    SELECT r.ix, r.iy, avg(n.weight) AS avg_weight
    FROM raw r
    JOIN raw n
      ON abs(n.ix - r.ix) <= 1
     AND abs(n.iy - r.iy) <= 1
     AND NOT (n.ix = r.ix AND n.iy = r.iy)
    GROUP BY r.ix, r.iy
  )
  SELECT
    r.ix,
    r.iy,
    r.lng,
    r.lat,
    least(
      12::numeric,
      greatest(
        0.15::numeric,
        CASE
          WHEN r.point_count = 1 AND neigh.avg_weight IS NULL THEN
            0.35 * (0.7 * r.weight + 0.3 * coalesce(glob.avg_weight, r.weight))
          ELSE
            0.7 * r.weight + 0.3 * coalesce(neigh.avg_weight, r.weight)
        END
      )
    ) AS weight,
    r.point_count,
    r.report_count,
    greatest(1, least(100, coalesce(r.max_severity, 1))),
    now()
  FROM raw r
  CROSS JOIN glob
  LEFT JOIN neigh ON neigh.ix = r.ix AND neigh.iy = r.iy
  ORDER BY 5 DESC
  LIMIT 4000;

  UPDATE public.garba_vortex_storm_state
     SET snapshot_refreshed_at = now()
   WHERE id = 1;

  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.refresh_garba_vortex_heatmap_snapshot(boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.refresh_garba_vortex_heatmap_snapshot(boolean) FROM anon;
REVOKE ALL ON FUNCTION public.refresh_garba_vortex_heatmap_snapshot(boolean) FROM authenticated;

COMMENT ON FUNCTION public.refresh_garba_vortex_heatmap_snapshot(boolean) IS
  'Owner-only. Rebuilds the averaged storm heatmap. Skips work inside the TTL unless p_force. Isolated-spike weights are not used.';

-- ---------------------------------------------------------------------------
-- Heatmap. DEFINER so anon can trip evaluate/refresh without EXECUTE on them.
-- hidden_at rows stay excluded (same visible set as the invoker version).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_garba_vortex_heatmap(
  p_min_lng double precision,
  p_min_lat double precision,
  p_max_lng double precision,
  p_max_lat double precision,
  p_zoom double precision DEFAULT 4,
  p_include_reports boolean DEFAULT true
)
RETURNS TABLE (
  lng double precision,
  lat double precision,
  weight numeric,
  point_count integer,
  max_severity integer,
  isolated boolean,
  black_hole boolean
)
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, extensions, net, pg_temp
AS $$
DECLARE
  v_active boolean := false;
  v_eval timestamptz;
  v_have boolean := false;
  v_meters double precision;
  v_mid_lat double precision;
  v_cos double precision;
  v_dlat double precision;
  v_dlng double precision;
  v_bh integer;
  v_spikes boolean;
BEGIN
  IF p_min_lng IS NULL OR p_min_lat IS NULL OR p_max_lng IS NULL OR p_max_lat IS NULL THEN
    RETURN;
  END IF;

  SELECT s.active, s.evaluated_at
    INTO v_active, v_eval
  FROM public.garba_vortex_storm_state s
  WHERE s.id = 1;

  IF v_eval IS NULL OR v_eval < now() - interval '5 seconds' THEN
    v_active := public.garba_vortex_evaluate_storm();
  END IF;
  v_active := coalesce(v_active, false);

  IF v_active THEN
    PERFORM public.refresh_garba_vortex_heatmap_snapshot(false);
    SELECT EXISTS (SELECT 1 FROM public.garba_vortex_heatmap_snapshot) INTO v_have;
    IF v_have THEN
      RETURN QUERY
      SELECT
        s.lng,
        s.lat,
        CASE
          WHEN coalesce(p_include_reports, true) OR s.report_count <= 0 THEN s.weight
          ELSE s.weight * (s.point_count - s.report_count)::numeric / greatest(s.point_count, 1)
        END AS weight,
        CASE
          WHEN coalesce(p_include_reports, true) THEN s.point_count
          ELSE (s.point_count - s.report_count)
        END AS point_count,
        s.max_severity,
        false AS isolated,
        false AS black_hole
      FROM public.garba_vortex_heatmap_snapshot s
      WHERE s.lat BETWEEN least(p_min_lat, p_max_lat) AND greatest(p_min_lat, p_max_lat)
        AND (
          (
            p_min_lng <= p_max_lng
            AND s.lng BETWEEN p_min_lng AND p_max_lng
          )
          OR (
            p_min_lng > p_max_lng
            AND (s.lng >= p_min_lng OR s.lng <= p_max_lng)
          )
        )
        AND (
          coalesce(p_include_reports, true)
          OR s.point_count > s.report_count
        )
      ORDER BY 3 DESC
      LIMIT 2000;
      RETURN;
    END IF;
  END IF;

  IF v_active THEN
    SELECT greatest(coalesce(storm_cell_m, 8000), 500)::double precision
      INTO v_meters
    FROM public.garba_vortex_config
    WHERE id = 1;
    v_meters := coalesce(v_meters, 8000);
  ELSE
    v_meters := public.garba_vortex_cell_m(p_zoom);
  END IF;

  v_spikes := NOT v_active;
  v_mid_lat := (least(p_min_lat, p_max_lat) + greatest(p_min_lat, p_max_lat)) / 2.0;
  v_cos := greatest(cos(radians(v_mid_lat)), 0.2);
  v_dlat := v_meters / 111320.0;
  v_dlng := v_meters / (111320.0 * v_cos);

  SELECT black_hole_min_severity INTO v_bh
  FROM public.garba_vortex_config
  WHERE id = 1;
  v_bh := coalesce(v_bh, 8);

  RETURN QUERY
  SELECT
    avg(m.location_lng)::double precision AS lng,
    avg(m.location_lat)::double precision AS lat,
    (
      CASE
        WHEN v_spikes AND count(*) = 1 AND bool_or(m.is_isolated) THEN
          least(12::numeric, 8::numeric + max(m.severity_score)::numeric / 20.0)
        ELSE
          least(
            12::numeric,
            2.5
              + ln(count(*)::numeric + 1) * 1.7
              + ln(sum(m.severity_score)::numeric + 1) * 0.35
          )
      END
    ) AS weight,
    count(*)::integer AS point_count,
    max(m.severity_score)::integer AS max_severity,
    CASE WHEN v_spikes THEN bool_or(m.is_isolated) ELSE false END AS isolated,
    (
      v_spikes
      AND count(*) = 1
      AND bool_or(m.is_isolated)
      AND max(m.severity_score) >= v_bh
    ) AS black_hole
  FROM public.missions m
  WHERE m.hidden_at IS NULL
    AND m.location_lat IS NOT NULL
    AND m.location_lng IS NOT NULL
    AND m.location_lat BETWEEN least(p_min_lat, p_max_lat) AND greatest(p_min_lat, p_max_lat)
    AND (
      (
        p_min_lng <= p_max_lng
        AND m.location_lng BETWEEN p_min_lng AND p_max_lng
      )
      OR (
        p_min_lng > p_max_lng
        AND (m.location_lng >= p_min_lng OR m.location_lng <= p_max_lng)
      )
    )
    AND public.garba_vortex_pin_visible(
      m.status::text,
      m.hidden_at,
      m.created_at,
      m.current_funding,
      m.history_public_until,
      m.media_purged_at
    )
    AND (
      coalesce(p_include_reports, true)
      OR NOT (
        coalesce(m.is_report, false)
        OR lower(coalesce(m.status::text, '')) = 'reported'
      )
    )
  GROUP BY
    round(m.location_lat / v_dlat),
    round(m.location_lng / v_dlng)
  ORDER BY 3 DESC
  LIMIT 2000;
END;
$$;

REVOKE ALL ON FUNCTION public.get_garba_vortex_heatmap(
  double precision, double precision, double precision, double precision, double precision, boolean
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_garba_vortex_heatmap(
  double precision, double precision, double precision, double precision, double precision, boolean
) TO anon, authenticated, service_role;

COMMENT ON FUNCTION public.get_garba_vortex_heatmap(
  double precision, double precision, double precision, double precision, double precision, boolean
) IS
  'Zoom-binned cells. During storm mode returns the averaged snapshot with isolated=false and black_hole=false. hidden_at rows are excluded. Does not move tokens.';

CREATE OR REPLACE FUNCTION public.get_garba_vortex_public_status()
RETURNS jsonb
LANGUAGE sql
VOLATILE
SECURITY DEFINER
SET search_path = public, extensions, net, pg_temp
AS $$
  SELECT jsonb_build_object(
    'storm', coalesce(s.active, false),
    'cache_seconds', CASE
      WHEN coalesce(s.active, false) THEN greatest(coalesce(c.storm_cache_seconds, 30), 5)
      ELSE 0
    END
  )
  FROM public.garba_vortex_config c
  LEFT JOIN public.garba_vortex_storm_state s ON s.id = 1
  WHERE c.id = 1;
$$;

REVOKE ALL ON FUNCTION public.get_garba_vortex_public_status() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_garba_vortex_public_status() TO anon, authenticated, service_role;

COMMENT ON FUNCTION public.get_garba_vortex_public_status() IS
  'Public storm flag and HTTP cache TTL. Does not return write counts.';

-- ---------------------------------------------------------------------------
-- Free pin. Same signature. Storm tightens cap + bump before the daily check.
-- The user advisory lock is taken before evaluate_storm so lock order stays
-- user-then-storm (the heatmap takes the storm lock only).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.place_free_vortex_pin(
  p_location_lat double precision,
  p_location_lng double precision,
  p_description text,
  p_photo_urls text[] DEFAULT ARRAY[]::text[],
  p_service_type text DEFAULT 'beach_street_cleanup',
  p_country text DEFAULT NULL,
  p_city text DEFAULT NULL,
  p_video_proof_url text DEFAULT NULL,
  p_commit boolean DEFAULT true
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions, net, pg_temp
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_service text;
  v_desc text;
  v_country text := nullif(btrim(coalesce(p_country, '')), '');
  v_city text := nullif(btrim(coalesce(p_city, '')), '');
  v_video text := nullif(btrim(coalesce(p_video_proof_url, '')), '');
  v_geog geography;
  v_cfg public.garba_vortex_config;
  v_bump_id uuid;
  v_bump_score integer;
  v_day_count integer;
  v_cell_count integer;
  v_cost integer := 0;
  v_balance integer;
  v_id uuid;
  v_sector uuid;
  v_storm boolean := false;
  v_daily_cap integer;
  v_bump_m integer;
  v_same_m integer;
  v_scope text;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_location_lat IS NULL OR p_location_lng IS NULL
     OR p_location_lat < -90 OR p_location_lat > 90
     OR p_location_lng < -180 OR p_location_lng > 180 THEN
    RAISE EXCEPTION 'Location required';
  END IF;

  SELECT * INTO v_cfg FROM public.garba_vortex_config WHERE id = 1;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'garba_vortex_config missing';
  END IF;

  v_service := lower(coalesce(nullif(btrim(p_service_type), ''), 'beach_street_cleanup'));
  IF NOT public.is_garbage_removal_service(v_service) THEN
    v_service := 'beach_street_cleanup';
  END IF;

  v_desc := nullif(btrim(coalesce(p_description, '')), '');
  IF v_desc IS NULL THEN
    v_desc := '#GarbageZone Needs attention';
  END IF;
  IF char_length(v_desc) > 2000 THEN
    RAISE EXCEPTION 'Description too long';
  END IF;

  IF v_video IS NOT NULL AND char_length(v_video) > 500 THEN
    RAISE EXCEPTION 'Video proof URL too long';
  END IF;

  IF v_country IS NOT NULL AND char_length(v_country) > 120 THEN
    v_country := left(v_country, 120);
  END IF;
  IF v_city IS NOT NULL AND char_length(v_city) > 120 THEN
    v_city := left(v_city, 120);
  END IF;

  v_geog := public.garba_vortex_point(p_location_lat, p_location_lng);

  IF p_commit THEN
    PERFORM pg_advisory_xact_lock(hashtext('garba-user:' || v_uid::text));
  END IF;

  v_storm := public.garba_vortex_evaluate_storm();
  IF v_storm THEN
    v_daily_cap := least(v_cfg.free_pins_per_day, greatest(0, v_cfg.storm_free_pins_per_day));
    v_bump_m := greatest(v_cfg.bump_radius_m, v_cfg.storm_bump_radius_m);
    v_same_m := greatest(v_cfg.same_spot_radius_m, v_cfg.storm_same_spot_radius_m);
    v_scope := 'any';
  ELSE
    v_daily_cap := v_cfg.free_pins_per_day;
    v_bump_m := v_cfg.bump_radius_m;
    v_same_m := v_cfg.same_spot_radius_m;
    v_scope := v_cfg.bump_scope;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.cleanup_sectors s
    WHERE s.status = 'cleanup'
      AND s.area IS NOT NULL
      AND ST_Covers(s.area, v_geog)
      AND public.garba_vortex_sector_order_open(s.mission_id)
  ) THEN
    RAISE EXCEPTION 'cleanup_sector_closed' USING ERRCODE = 'P0001';
  END IF;

  SELECT m.id, m.severity_score
    INTO v_bump_id, v_bump_score
  FROM public.missions m
  WHERE coalesce(m.is_report, false) = true
    AND m.hidden_at IS NULL
    AND lower(coalesce(m.status::text, '')) IN ('reported', 'pending', 'available', 'funding', 'open')
    AND m.created_at >= now() - make_interval(days => v_cfg.bump_recency_days)
    AND ST_DWithin(
      coalesce(m.location, public.garba_vortex_point(m.location_lat, m.location_lng)),
      v_geog,
      v_same_m
    )
  ORDER BY ST_Distance(
    coalesce(m.location, public.garba_vortex_point(m.location_lat, m.location_lng)),
    v_geog
  )
  LIMIT 1;

  IF v_bump_id IS NULL AND v_scope = 'any' THEN
    SELECT m.id, m.severity_score
      INTO v_bump_id, v_bump_score
    FROM public.missions m
    WHERE coalesce(m.is_report, false) = true
      AND m.hidden_at IS NULL
      AND lower(coalesce(m.status::text, '')) IN ('reported', 'pending', 'available', 'funding', 'open')
      AND m.created_at >= now() - make_interval(days => v_cfg.bump_recency_days)
      AND ST_DWithin(
        coalesce(m.location, public.garba_vortex_point(m.location_lat, m.location_lng)),
        v_geog,
        v_bump_m
      )
    ORDER BY ST_Distance(
      coalesce(m.location, public.garba_vortex_point(m.location_lat, m.location_lng)),
      v_geog
    )
    LIMIT 1;
  ELSIF v_bump_id IS NULL THEN
    SELECT m.id, m.severity_score
      INTO v_bump_id, v_bump_score
    FROM public.missions m
    WHERE m.creator_id = v_uid
      AND coalesce(m.is_report, false) = true
      AND m.hidden_at IS NULL
      AND lower(coalesce(m.status::text, '')) IN ('reported', 'pending', 'available', 'funding', 'open')
      AND m.created_at >= now() - make_interval(days => v_cfg.bump_recency_days)
      AND ST_DWithin(
        coalesce(m.location, public.garba_vortex_point(m.location_lat, m.location_lng)),
        v_geog,
        v_bump_m
      )
    ORDER BY ST_Distance(
      coalesce(m.location, public.garba_vortex_point(m.location_lat, m.location_lng)),
      v_geog
    )
    LIMIT 1;
  END IF;

  IF v_bump_id IS NOT NULL THEN
    v_bump_score := least(100, coalesce(v_bump_score, 1) + 1);
    IF NOT p_commit THEN
      RETURN jsonb_build_object(
        'ok', true,
        'action', 'bump',
        'id', v_bump_id,
        'severity_score', v_bump_score,
        'tokens_spent', 0,
        'storm', v_storm
      );
    END IF;

    UPDATE public.missions m
       SET severity_score = v_bump_score,
           photo_urls = coalesce(
             (
               SELECT array_agg(shot.u)
               FROM (
                 SELECT u
                 FROM unnest(
                   coalesce(m.photo_urls, ARRAY[]::text[])
                   || coalesce(p_photo_urls, ARRAY[]::text[])
                 ) AS u
                 WHERE nullif(btrim(u), '') IS NOT NULL
                 LIMIT 9
               ) AS shot
             ),
             m.photo_urls
           ),
           video_proof_url = coalesce(m.video_proof_url, v_video)
     WHERE m.id = v_bump_id;

    PERFORM public.garba_vortex_refresh_isolation(p_location_lat, p_location_lng);
    PERFORM public.garba_vortex_record_write(v_uid, p_location_lat, p_location_lng, 'bump');

    RETURN jsonb_build_object(
      'ok', true,
      'action', 'bumped',
      'id', v_bump_id,
      'severity_score', v_bump_score,
      'tokens_spent', 0,
      'storm', v_storm
    );
  END IF;

  SELECT count(*)::integer
    INTO v_day_count
  FROM public.missions m
  WHERE m.creator_id = v_uid
    AND coalesce(m.is_report, false) = true
    AND m.created_at >= now() - interval '1 day';

  IF v_day_count >= v_daily_cap THEN
    IF v_storm AND v_daily_cap < v_cfg.free_pins_per_day THEN
      RAISE EXCEPTION 'free_pin_storm_limit' USING ERRCODE = 'P0001';
    END IF;
    RAISE EXCEPTION 'free_pin_daily_limit' USING ERRCODE = 'P0001';
  END IF;

  SELECT count(*)::integer
    INTO v_cell_count
  FROM public.missions m
  WHERE coalesce(m.is_report, false) = true
    AND m.hidden_at IS NULL
    AND lower(coalesce(m.status::text, '')) IN ('reported', 'pending', 'available', 'funding', 'open')
    AND (SELECT c.grid_key FROM public.garba_vortex_cell(m.location_lat, m.location_lng, v_cfg.sector_grid_m) AS c)
      = (SELECT c.grid_key FROM public.garba_vortex_cell(p_location_lat, p_location_lng, v_cfg.sector_grid_m) AS c);

  IF v_cfg.high_risk_token_cost > 0 AND v_cell_count >= v_cfg.high_risk_min_pins THEN
    v_cost := v_cfg.high_risk_token_cost;
  END IF;

  IF NOT p_commit THEN
    RETURN jsonb_build_object(
      'ok', true,
      'action', 'create',
      'tokens_spent', v_cost,
      'high_risk', v_cost > 0,
      'storm', v_storm
    );
  END IF;

  IF p_photo_urls IS NULL OR coalesce(cardinality(p_photo_urls), 0) < 1 THEN
    RAISE EXCEPTION 'At least one photo is required';
  END IF;

  IF v_cost > 0 THEN
    SELECT token_balance
      INTO v_balance
    FROM public.profiles
    WHERE id = v_uid
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Profile not found';
    END IF;
    IF coalesce(v_balance, 0) < v_cost THEN
      RAISE EXCEPTION 'insufficient_tokens' USING ERRCODE = 'P0001';
    END IF;

    UPDATE public.profiles
       SET token_balance = token_balance - v_cost
     WHERE id = v_uid;
  END IF;

  INSERT INTO public.missions (
    creator_id,
    category,
    service_type,
    status,
    is_report,
    crowdfunding_mode,
    amount_target,
    expected_price,
    current_funding,
    location_lat,
    location_lng,
    description,
    photo_urls,
    video_proof_url,
    country,
    city,
    crowdfunding_expires_at,
    severity_score,
    is_isolated
  )
  VALUES (
    v_uid,
    'public',
    v_service,
    'reported',
    true,
    false,
    0,
    0,
    0,
    p_location_lat,
    p_location_lng,
    v_desc,
    p_photo_urls[1:9],
    v_video,
    v_country,
    v_city,
    now() + interval '7 days',
    1,
    true
  )
  RETURNING id INTO v_id;

  PERFORM public.garba_vortex_refresh_isolation(p_location_lat, p_location_lng);
  v_sector := public.garba_vortex_rollup_sector(
    p_location_lat,
    p_location_lng,
    v_uid,
    v_country,
    v_city
  );
  PERFORM public.garba_vortex_record_write(v_uid, p_location_lat, p_location_lng, 'create');

  RETURN jsonb_build_object(
    'ok', true,
    'action', 'created',
    'id', v_id,
    'severity_score', 1,
    'tokens_spent', v_cost,
    'sector_id', v_sector,
    'storm', v_storm
  );
END;
$$;

REVOKE ALL ON FUNCTION public.place_free_vortex_pin(
  double precision, double precision, text, text[], text, text, text, text, boolean
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.place_free_vortex_pin(
  double precision, double precision, text, text[], text, text, text, text, boolean
) FROM anon;
GRANT EXECUTE ON FUNCTION public.place_free_vortex_pin(
  double precision, double precision, text, text[], text, text, text, text, boolean
) TO authenticated, service_role;

COMMENT ON FUNCTION public.place_free_vortex_pin(
  double precision, double precision, text, text[], text, text, text, text, boolean
) IS
  'Free civic pin. Calm: daily cap, own-user 200 m bump, 35 m same-spot bump. Storm: tighter daily cap, any-user bump at the wider radius, free_pin_storm_limit when that cap is what rejects the row.';

-- ---------------------------------------------------------------------------
-- Admin indicator. Counts stay here; the public status RPC does not return them.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_get_garba_vortex_storm()
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, extensions, net, pg_temp
AS $$
DECLARE
  v_cfg public.garba_vortex_config;
  v_state public.garba_vortex_storm_state;
  v_cells integer := 0;
  v_snap timestamptz;
BEGIN
  IF NOT (
    coalesce(auth.jwt() ->> 'role', '') = 'service_role'
    OR public.is_platform_admin(auth.uid())
  ) THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  PERFORM public.garba_vortex_evaluate_storm();

  SELECT * INTO v_cfg FROM public.garba_vortex_config WHERE id = 1;
  SELECT * INTO v_state FROM public.garba_vortex_storm_state WHERE id = 1;
  SELECT count(*)::integer, max(refreshed_at)
    INTO v_cells, v_snap
  FROM public.garba_vortex_heatmap_snapshot;

  RETURN jsonb_build_object(
    'storm', coalesce(v_state.active, false),
    'reason', coalesce(v_state.reason, 'clear'),
    'mode', coalesce(v_cfg.storm_mode, 'auto'),
    'global_writes', coalesce(v_state.global_writes, 0),
    'global_threshold', v_cfg.storm_global_writes_per_minute,
    'peak_region_writes', coalesce(v_state.peak_region_writes, 0),
    'peak_region_key', v_state.peak_region_key,
    'region_threshold', v_cfg.storm_region_writes_per_minute,
    'region_km', v_cfg.storm_region_km,
    'evaluated_at', v_state.evaluated_at,
    'active_since', v_state.active_since,
    'snapshot_refreshed_at', coalesce(v_snap, v_state.snapshot_refreshed_at),
    'snapshot_cells', coalesce(v_cells, 0),
    'cache_seconds', v_cfg.storm_cache_seconds,
    'snapshot_ttl_seconds', v_cfg.storm_snapshot_ttl_seconds,
    'cooldown_seconds', v_cfg.storm_cooldown_seconds,
    'release_ratio', v_cfg.storm_release_ratio,
    'storm_free_pins_per_day', v_cfg.storm_free_pins_per_day,
    'storm_bump_radius_m', v_cfg.storm_bump_radius_m,
    'storm_same_spot_radius_m', v_cfg.storm_same_spot_radius_m,
    'storm_cell_m', v_cfg.storm_cell_m,
    'free_pins_per_day', v_cfg.free_pins_per_day,
    'bump_radius_m', v_cfg.bump_radius_m
  );
END;
$$;

REVOKE ALL ON FUNCTION public.admin_get_garba_vortex_storm() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_get_garba_vortex_storm() FROM anon;
GRANT EXECUTE ON FUNCTION public.admin_get_garba_vortex_storm() TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.admin_set_garba_vortex_storm(
  p_mode text DEFAULT NULL,
  p_global_writes_per_minute integer DEFAULT NULL,
  p_region_writes_per_minute integer DEFAULT NULL,
  p_storm_free_pins_per_day integer DEFAULT NULL,
  p_storm_bump_radius_m integer DEFAULT NULL,
  p_refresh boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public, extensions, net, pg_temp
AS $$
DECLARE
  v_before jsonb;
  v_after jsonb;
BEGIN
  IF NOT (
    coalesce(auth.jwt() ->> 'role', '') = 'service_role'
    OR public.is_platform_admin(auth.uid())
  ) THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  IF p_mode IS NOT NULL AND p_mode NOT IN ('off', 'auto', 'on') THEN
    RAISE EXCEPTION 'storm_mode must be off, auto, or on';
  END IF;
  IF p_global_writes_per_minute IS NOT NULL
     AND (p_global_writes_per_minute < 1 OR p_global_writes_per_minute > 100000) THEN
    RAISE EXCEPTION 'storm_global_writes_per_minute out of range';
  END IF;
  IF p_region_writes_per_minute IS NOT NULL
     AND (p_region_writes_per_minute < 1 OR p_region_writes_per_minute > 100000) THEN
    RAISE EXCEPTION 'storm_region_writes_per_minute out of range';
  END IF;
  IF p_storm_free_pins_per_day IS NOT NULL
     AND (p_storm_free_pins_per_day < 0 OR p_storm_free_pins_per_day > 50) THEN
    RAISE EXCEPTION 'storm_free_pins_per_day out of range';
  END IF;
  IF p_storm_bump_radius_m IS NOT NULL
     AND (p_storm_bump_radius_m < 1 OR p_storm_bump_radius_m > 50000) THEN
    RAISE EXCEPTION 'storm_bump_radius_m out of range';
  END IF;

  v_before := jsonb_build_object(
    'config', (SELECT to_jsonb(c) FROM public.garba_vortex_config c WHERE c.id = 1),
    'state', (SELECT to_jsonb(s) FROM public.garba_vortex_storm_state s WHERE s.id = 1)
  );

  UPDATE public.garba_vortex_config
     SET storm_mode = coalesce(p_mode, storm_mode),
         storm_global_writes_per_minute = coalesce(p_global_writes_per_minute, storm_global_writes_per_minute),
         storm_region_writes_per_minute = coalesce(p_region_writes_per_minute, storm_region_writes_per_minute),
         storm_free_pins_per_day = coalesce(p_storm_free_pins_per_day, storm_free_pins_per_day),
         storm_bump_radius_m = coalesce(p_storm_bump_radius_m, storm_bump_radius_m),
         updated_at = now()
   WHERE id = 1;

  PERFORM public.garba_vortex_evaluate_storm();
  IF coalesce(p_refresh, false) THEN
    PERFORM public.refresh_garba_vortex_heatmap_snapshot(true);
  END IF;

  v_after := jsonb_build_object(
    'config', (SELECT to_jsonb(c) FROM public.garba_vortex_config c WHERE c.id = 1),
    'state', (SELECT to_jsonb(s) FROM public.garba_vortex_storm_state s WHERE s.id = 1),
    'refresh', coalesce(p_refresh, false)
  );

  IF EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'private'
      AND p.proname = 'write_admin_audit'
  ) THEN
    PERFORM private.write_admin_audit(
      'garba_vortex_storm',
      'garba_vortex_config',
      '1',
      v_before,
      v_after
    );
  END IF;

  RETURN public.admin_get_garba_vortex_storm();
END;
$$;

REVOKE ALL ON FUNCTION public.admin_set_garba_vortex_storm(text, integer, integer, integer, integer, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_set_garba_vortex_storm(text, integer, integer, integer, integer, boolean) FROM anon;
GRANT EXECUTE ON FUNCTION public.admin_set_garba_vortex_storm(text, integer, integer, integer, integer, boolean) TO authenticated, service_role;

COMMENT ON FUNCTION public.admin_set_garba_vortex_storm(text, integer, integer, integer, integer, boolean) IS
  'Platform admin. Null arguments keep the current tune. p_refresh rebuilds the averaged snapshot. Writes one admin_audit_log row.';

-- ---------------------------------------------------------------------------
-- Post-flight
-- ---------------------------------------------------------------------------
DO $pf$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'garba_vortex_config'
      AND column_name = 'storm_mode'
  ) THEN
    RAISE EXCEPTION 'Post-flight failed: storm_mode missing';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.garba_vortex_storm_state WHERE id = 1) THEN
    RAISE EXCEPTION 'Post-flight failed: storm state row missing';
  END IF;

  IF has_function_privilege('anon', 'public.garba_vortex_evaluate_storm()', 'EXECUTE') THEN
    RAISE EXCEPTION 'Post-flight failed: anon can execute garba_vortex_evaluate_storm';
  END IF;

  IF has_function_privilege(
    'anon',
    'public.garba_vortex_record_write(uuid, double precision, double precision, text)',
    'EXECUTE'
  ) THEN
    RAISE EXCEPTION 'Post-flight failed: anon can execute garba_vortex_record_write';
  END IF;

  IF has_function_privilege('anon', 'public.refresh_garba_vortex_heatmap_snapshot(boolean)', 'EXECUTE') THEN
    RAISE EXCEPTION 'Post-flight failed: anon can execute refresh_garba_vortex_heatmap_snapshot';
  END IF;

  IF has_function_privilege('anon', 'public.admin_set_garba_vortex_storm(text, integer, integer, integer, integer, boolean)', 'EXECUTE') THEN
    RAISE EXCEPTION 'Post-flight failed: anon can execute admin_set_garba_vortex_storm';
  END IF;

  IF has_function_privilege('anon', 'public.admin_get_garba_vortex_storm()', 'EXECUTE') THEN
    RAISE EXCEPTION 'Post-flight failed: anon can execute admin_get_garba_vortex_storm';
  END IF;

  IF NOT has_function_privilege('anon', 'public.get_garba_vortex_public_status()', 'EXECUTE') THEN
    RAISE EXCEPTION 'Post-flight failed: anon cannot execute get_garba_vortex_public_status';
  END IF;

  IF NOT has_function_privilege(
    'anon',
    'public.get_garba_vortex_heatmap(double precision, double precision, double precision, double precision, double precision, boolean)',
    'EXECUTE'
  ) THEN
    RAISE EXCEPTION 'Post-flight failed: anon cannot execute get_garba_vortex_heatmap';
  END IF;

  IF has_function_privilege(
    'anon',
    'public.place_free_vortex_pin(double precision, double precision, text, text[], text, text, text, text, boolean)',
    'EXECUTE'
  ) THEN
    RAISE EXCEPTION 'Post-flight failed: anon can execute place_free_vortex_pin';
  END IF;

  IF has_table_privilege('anon', 'public.garba_vortex_write_events', 'SELECT')
     OR has_table_privilege('authenticated', 'public.garba_vortex_write_events', 'SELECT') THEN
    RAISE EXCEPTION 'Post-flight failed: clients can read garba_vortex_write_events';
  END IF;

  IF has_table_privilege('anon', 'public.garba_vortex_heatmap_snapshot', 'SELECT') THEN
    RAISE EXCEPTION 'Post-flight failed: anon can read the storm snapshot directly';
  END IF;
END
$pf$;
